blank_issues_enabled: true
contact_links:
  - name: Documentation
    url: https://github.com/BSPLAZA/WhisperKey/tree/main/docs
    about: Check the documentation for answers to common questions
  - name: Discussions
    url: https://github.com/BSPLAZA/WhisperKey/discussions
    about: Ask questions and discuss ideas with the community