name: Swift CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    name: Build and Test
    runs-on: macos-latest
    
    strategy:
      matrix:
        xcode: ['15.0']
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Select Xcode
      run: sudo xcode-select -s /Applications/Xcode_${{ matrix.xcode }}.app
    
    - name: Show Xcode version
      run: xcodebuild -version
    
    - name: Resolve Package Dependencies
      run: |
        cd WhisperKey
        xcodebuild -resolvePackageDependencies -project WhisperKey.xcodeproj -scheme WhisperKey
    
    - name: Build
      run: |
        cd WhisperKey
        xcodebuild build -project WhisperKey.xcodeproj \
          -scheme WhisperKey \
          -destination 'platform=macOS' \
          -configuration Release \
          ONLY_ACTIVE_ARCH=NO
    
    - name: Run Tests
      run: |
        cd WhisperKey
        xcodebuild test -project WhisperKey.xcodeproj \
          -scheme WhisperKey \
          -destination 'platform=macOS' \
          -configuration Debug \
          -enableCodeCoverage YES \
          | xcpretty --test --color || exit 1
      continue-on-error: true

  swiftlint:
    name: SwiftLint
    runs-on: macos-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Install SwiftLint
      run: brew install swiftlint
    
    - name: Run SwiftLint
      run: |
        cd WhisperKey
        swiftlint --reporter github-actions-logging
      continue-on-error: true