name: Swift CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    name: Build and Test
    runs-on: macos-latest
    timeout-minutes: 30
    
    strategy:
      matrix:
        xcode: ['16.1']
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Cache Swift Package Manager
      uses: actions/cache@v3
      with:
        path: |
          .build
          ~/Library/Developer/Xcode/DerivedData
        key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-spm-
    
    - name: Select Xcode
      run: |
        if [[ "${{ matrix.xcode }}" =~ ^[0-9]+\.[0-9]+$ ]]; then
          sudo xcode-select -s "/Applications/Xcode_${{ matrix.xcode }}.app"
        else
          echo "Invalid Xcode version format"
          exit 1
        fi
    
    - name: Show Xcode version
      run: xcodebuild -version
    
    - name: Install xcpretty
      run: gem install xcpretty
    
    - name: Build whisper.cpp
      run: |
        echo "Building whisper.cpp for CI..."
        cd ~
        git clone https://github.com/ggerganov/whisper.cpp
        cd whisper.cpp
        # Use a specific commit for reproducibility
        git checkout 4bbb60efb1de8d436088064b1950a2e46089fec9
        WHISPER_METAL=1 make -j
        mkdir -p ~/Developer/whisper.cpp/build/bin
        cp main ~/Developer/whisper.cpp/build/bin/whisper-cli
        # Copy required libraries
        mkdir -p ~/Developer/whisper.cpp/lib
        find . -name "*.dylib" -type f -exec cp {} ~/Developer/whisper.cpp/lib/ \;
    
    - name: Build
      run: |
        xcodebuild build -project WhisperKey/WhisperKey.xcodeproj \
          -scheme WhisperKey \
          -destination 'platform=macOS' \
          -configuration Release \
          ONLY_ACTIVE_ARCH=NO
    
    - name: Run Tests
      run: |
        xcodebuild test -project WhisperKey/WhisperKey.xcodeproj \
          -scheme WhisperKey \
          -destination 'platform=macOS' \
          -configuration Debug \
          -enableCodeCoverage YES \
          | xcpretty --test --color || exit 1
      continue-on-error: true

  swiftlint:
    name: SwiftLint
    runs-on: macos-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Install SwiftLint
      run: brew install swiftlint
    
    - name: Run SwiftLint
      run: |
        swiftlint --reporter github-actions-logging
      continue-on-error: true